title: wardn
description: Encrypted Bitwarden vault backups
remote_theme: just-the-docs/just-the-docs
url: https://rayvn.ink
baseurl: /wardn

nav_external_links:
  - title: GitHub
    url: https://github.com/phoggy/wardn
  - title: rayvn docs
    url: /rayvn
  - title: valt docs
    url: /valt

aux_links:
  "rayvn.ink": "/"
